import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { IoIosAddCircleOutline } from "react-icons/io";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="light" lang="en">
      <body className={inter.className}>
        <nav className="flex justify-between items-center p-2">
          <Link href={"/"} className="btn btn-ghost">
            <h1 className="text-2xl font-bold">TODO</h1>
          </Link>

          <Link href={"/create"} className="btn btn-ghost">
            <div>Create</div>
          </Link>
        </nav>
        <main className="select-none">{children}</main>
      </body>
    </html>
  );
}
